# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Austin Green
email: austingreenkansas@gmail.com
description: >
  This template is availabe for free use on my GitHub account.
baseurl: ""
url:
github_username:  austin94
markdown: kramdown
